// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.utility.dashboard').requires('impact.entity', 'game.entities.gui.guiImage', 'game.entities.gui.pauseScreen').defines(function() {
    return window.EntityDashboard = ig.Entity.extend({
      font: new ig.Font('media/helvetica24EEE.png'),
      spacing: 28,
      barLength: 200,
      init: function() {
        var pauseButton;
        this.pos = {
          x: 5,
          y: 5
        };
        pauseButton = ig.game.spawnEntity(EntityGuiImage, 850, 530, {
          fileName: "pause.png"
        });
        return pauseButton.onclick = function() {
          return ig.game.spawnEntity(EntityPauseScreen);
        };
      },
      draw: function() {
        this.font.draw("$" + ig.game.stats.money, this.pos.x, this.pos.y);
        this.drawProgressBar('addition', '+', 'blue', 0.15, 0);
        this.drawProgressBar('subtraction', '-', 'blue', 0.15, 1);
        this.drawProgressBar('multiplication', 'X', 'blue', 0.15, 2);
        return this.drawProgressBar('division', '%', 'blue', 0.15, 3);
      },
      drawProgressBar: function(stat, symbol, fillColor, padPercent, position) {
        var experience, experienceRequired, level, padding, percent, yValue;
        padding = this.spacing * (1 + padPercent);
        yValue = this.pos.y + padding + position * this.spacing;
        experience = ig.game.stats[stat].experience;
        level = ig.game.stats[stat].level;
        experienceRequired = ig.game.experienceRequired(level);
        percent = experience / experienceRequired;
        this.font.draw(symbol, this.pos.x, this.pos.y + this.spacing * (position + 1));
        this.font.draw(level, this.pos.x + padding, this.pos.y + this.spacing * (position + 1));
        this.drawRect(this.pos.x + padding * 2, yValue, this.barLength, this.spacing / 2, 'white');
        this.drawRect(this.pos.x + padding * 2, yValue, percent * this.barLength, this.spacing / 2, fillColor);
        return this.font.draw("" + experience + "/" + experienceRequired, this.pos.x + this.barLength + this.spacing * 3, yValue - 10);
      },
      drawRect: function(x, y, width, height, color) {
        var ctx, s;
        ctx = ig.system.context;
        s = ig.system.scale;
        ctx.fillStyle = color;
        return ctx.fillRect(x * s, y * s, width * s, height * s);
      }
    });
  });

}).call(this);
