// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.utility.message').requires('impact.entity').defines(function() {
    return window.EntityMessage = ig.Entity.extend({
      font: new ig.Font('media/helvetica30EEE.png'),
      centering: ig.Font.ALIGN.CENTER,
      lifetime: 1,
      init: function(message) {
        this.messages = message.split('/n');
        this.idleTimer = new ig.Timer();
        return this.pos = {
          x: ig.system.width / 2,
          y: ig.system.height / 2
        };
      },
      update: function() {
        if (this.idleTimer.delta() > this.lifetime) {
          return this.kill();
        }
      },
      draw: function() {
        var i, _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.messages.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(this.font.draw(this.messages[i], this.pos.x + 18, this.pos.y + 30 * i, this.centering));
        }
        return _results;
      }
    });
  });

}).call(this);
