// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.centeredTextBox').requires('game.entities.gui.textBox').defines(function() {
    return window.EntityCenteredTextBox = EntityTextBox.extend({
      drawText: function(text) {
        var center, i, line, yStart, _i, _ref, _results;
        center = this.y + this.height / 2;
        yStart = center - text.length * this.fontHeight / 2;
        _results = [];
        for (i = _i = 0, _ref = text.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          line = text[i];
          _results.push(this.font.draw(line, this.x + this.width / 2, yStart + i * this.fontHeight, ig.Font.ALIGN.CENTER));
        }
        return _results;
      }
    });
  });

}).call(this);
