// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.centeredTextBox').requires('game.entities.gui.textBox').defines(function() {
    return window.EntityCenteredTextBox = EntityTextBox.extend({
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        this.ctx.textAlign = 'center';
        return this.ctx.textBaseline = 'middle';
      },
      drawText: function() {
        return this.ctx.fillText(this.text, this.x + this.width / 2, this.y + this.height / 2);
      }
    });
  });

}).call(this);
