// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.completedLevel').requires('game.entities.gui.rectangle', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityCompletedLevel = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.parent(100, 100, settings);
        this.width = ig.system.width - 200;
        this.height = ig.system.height - 200;
        this.backgroundColor = '#ddd';
        this.borderColor = '#975';
        this.borderSize = 3;
        return ig.game.spawnEntity(EntityCenteredTextBox, ig.system.width / 2 - 100, ig.system.height - 250, {
          width: 200,
          height: 50,
          backgroundColor: 'white',
          borderColor: 'green',
          borderSize: '2',
          text: 'Helloooo',
          zIndex: 10
        });
      }
    });
  });

}).call(this);
