// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.completedLevel').requires('game.entities.gui.rectangle', 'game.entities.gui.textBox', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityCompletedLevel = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.parent(100, 100, settings);
        this.width = ig.system.width - 200;
        this.height = ig.system.height - 200;
        this.backgroundColor = '#ddd';
        this.borderColor = '#975';
        this.borderSize = 3;
        ig.game.spawnEntity(EntityTextBox, 150, 150, {
          width: ig.system.width - 300,
          height: ig.system.height - 400,
          backgroundColor: 'white',
          borderColor: 'black',
          borderSize: '2',
          zIndex: 10,
          text: "Blessings upon you, fair traveller. ~              You have plumbed the depths of the labyrinth and found your treasure.              Take as your reward $" + settings.money + " and the knowledge that you have              discovered the lost treasure of " + settings.id + "."
        });
        this.acceptBox = ig.game.spawnEntity(EntityCenteredTextBox, ig.system.width / 2 - 100, ig.system.height - 200, {
          width: 200,
          height: 50,
          backgroundColor: 'white',
          borderColor: 'green',
          borderSize: '2',
          text: 'Accept',
          zIndex: 10
        });
        return this.acceptBox.onclick = function() {
          ig.game.goToCenter();
          return this.kill();
        };
      },
      update: function() {
        this.parent();
        if (ig.input.pressed('accept')) {
          return this.acceptBox.onclick();
        }
      }
    });
  });

}).call(this);
