// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.creditsScreen').requires('game.entities.gui.screen', 'game.entities.gui.centeredTextBox', 'game.entities.gui.guiImage').defines(function() {
    return window.EntityCreditsScreen = EntityScreen.extend({
      init: function(x, y, settings) {
        var backButton, textBox,
          _this = this;
        this.parent(0, 0, settings);
        textBox = ig.game.spawnEntity(EntityCenteredTextBox, ig.system.width / 2 - 350, 50, {
          width: 700,
          height: 400,
          backgroundColor: 'white',
          borderColor: 'black',
          borderSize: '2',
          zIndex: 25,
          text: "Jeffrey Biles (@jeffreybiles) - Programming and game design ~              Pablo Velasquez (@pablovem) - Art ~              Chad Robb - Music, maybe"
        });
        backButton = ig.game.spawnEntity(EntityCenteredTextBox, 350, 500, {
          width: 260,
          height: 100,
          zIndex: 25,
          text: 'Back'
        });
        backButton.onclick = function() {
          if (_this.timer.delta() > 0) {
            return _this.kill();
          }
        };
        return this.children = [textBox, backButton];
      },
      update: function() {
        if (ig.input.pressed('accept')) {
          return this.kill();
        }
      }
    });
  });

}).call(this);
