// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.guiImage').requires('game.entities.gui.rectangle').defines(function() {
    return window.EntityGuiImage = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.image = new ig.Image("media/" + settings.fileName);
        settings['width'] = this.image.width;
        settings['height'] = this.image.height;
        return this.parent(x, y, settings);
      },
      draw: function() {
        return this.image.draw(this.x, this.y);
      }
    });
  });

}).call(this);
