// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.openLevel').requires('game.entities.gui.screen', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityOpenLevel = EntityScreen.extend({
      font: new ig.Font('media/helvetica24000.png'),
      init: function(x, y, settings) {
        var noButton, textButton, yesButton,
          _this = this;
        this.parent(0, 0, settings);
        this.playerAnswer = "";
        textButton = ig.game.spawnEntity(EntityCenteredTextBox, 200, 100, {
          width: 560,
          height: 100,
          zIndex: 15,
          text: "You can open this level up for only $" + settings.amount + ". ~            Would you like to do it?"
        });
        yesButton = ig.game.spawnEntity(EntityCenteredTextBox, 530, 250, {
          width: 230,
          height: 100,
          text: 'Yes (y)',
          zIndex: 15
        });
        yesButton.onclick = function() {
          return _this.playerAnswer = 'y';
        };
        noButton = ig.game.spawnEntity(EntityCenteredTextBox, 200, 250, {
          width: 230,
          height: 100,
          text: 'No (n)',
          zIndex: 15
        });
        noButton.onclick = function() {
          return _this.playerAnswer = 'n';
        };
        return this.children = [textButton, yesButton, noButton];
      }
    });
  });

}).call(this);
