// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.pauseScreen').requires('game.entities.gui.rectangle', 'game.entities.gui.textBox', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityPauseScreen = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.parent(0, 0, settings);
        this.width = ig.system.width;
        this.height = ig.system.height;
        this.backgroundColor = '#ddd';
        this.borderColor = '#975';
        this.borderSize = 3;
        this.children = [
          ig.game.spawnEntity(EntityTextBox, 50, 50, {
            width: ig.system.width - 100,
            height: ig.system.height - 100,
            backgroundColor: 'white',
            borderColor: 'black',
            borderSize: '2',
            zIndex: 10,
            text: "Pause"
          })
        ];
        return ig.game.state = 'paused';
      },
      update: function() {
        this.parent();
        if (ig.input.pressed('accept')) {
          ig.game.state = 'main';
          return this.kill();
        }
      },
      kill: function() {
        var child, _i, _len, _ref;
        _ref = this.children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          child.kill();
        }
        return this.parent();
      }
    });
  });

}).call(this);
