// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.pauseScreen').requires('game.entities.gui.screen', 'game.entities.gui.centeredTextBox', 'game.entities.gui.guiImage').defines(function() {
    return window.EntityPauseScreen = EntityScreen.extend({
      init: function(x, y, settings) {
        var goToCenterButton, resumeButton, textBox,
          _this = this;
        this.parent(0, 0, settings);
        textBox = ig.game.spawnEntity(EntityCenteredTextBox, ig.system.width / 2 - 100, 50, {
          width: 200,
          height: 100,
          backgroundColor: 'white',
          borderColor: 'black',
          borderSize: '2',
          zIndex: 10,
          text: "Pause"
        });
        resumeButton = ig.game.spawnEntity(EntityGuiImage, 500, 200, {
          fileName: "resumeLevel.png",
          zIndex: 15
        });
        resumeButton.onclick = function() {
          return _this.kill();
        };
        goToCenterButton = ig.game.spawnEntity(EntityGuiImage, 200, 200, {
          fileName: "goToCenter.png",
          zIndex: 15
        });
        goToCenterButton.onclick = function() {
          return ig.game.goToCenter();
        };
        return this.children = [textBox, resumeButton, goToCenterButton];
      },
      kill: function() {
        ig.game.state = 'main';
        return this.parent();
      },
      update: function() {
        this.parent();
        if (ig.input.pressed('accept')) {
          return this.kill();
        }
      }
    });
  });

}).call(this);
