// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.problemInterface').requires('game.entities.gui.rectangle', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityProblemInterface = EntityRectangle.extend({
      font: new ig.Font('media/helvetica24000.png'),
      init: function(x, y, settings) {
        var column, i, row, _i, _results;
        this.question = settings.question;
        this.parent(50, 50, {});
        this.width = 860;
        this.height = 540;
        this.buttonWidth = 130;
        this.buttonHeight = 130;
        this.playerAnswer = "";
        _results = [];
        for (i = _i = 1; _i <= 9; i = ++_i) {
          row = Math.floor((i - 1) / 3);
          column = (i - 1) % 3;
          _results.push(this.makeNumberButton(this.x + column * (this.buttonWidth + 10), this.y + row * (this.buttonHeight + 10), i));
        }
        return _results;
      },
      makeNumberButton: function(x, y, number) {
        var button,
          _this = this;
        button = ig.game.spawnEntity(EntityCenteredTextBox, x, y, {
          zIndex: 10,
          text: "" + number,
          width: this.buttonWidth,
          height: this.buttonHeight
        });
        button.onclick = function() {
          return _this.playerAnswer += "" + number;
        };
        return this.children.push(button);
      },
      draw: function() {
        this.parent();
        this.font.draw("The question is " + this.question, 500, 100);
        return this.font.draw("Your answer is " + this.playerAnswer, 500, 150);
      }
    });
  });

}).call(this);
