// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.problemInterface').requires('game.entities.gui.rectangle', 'game.entities.gui.centeredTextBox').defines(function() {
    return window.EntityProblemInterface = EntityRectangle.extend({
      font: new ig.Font('media/helvetica32000.png'),
      bigFont: new ig.Font('media/helvetica60000.png'),
      init: function(x, y, settings) {
        var acceptButton, column, i, row, _i,
          _this = this;
        this.padding = 10;
        this.question = settings.question;
        this.parent(50, 50, {});
        this.width = 860;
        this.height = 540;
        this.buttonWidth = 120;
        this.buttonHeight = 120;
        this.playerAnswer = "";
        this.textCenter = 650;
        for (i = _i = 1; _i <= 9; i = ++_i) {
          row = Math.floor((i - 1) / 3);
          column = (i - 1) % 3;
          this.makeNumberButton(this.x + this.padding + column * (this.buttonWidth + 10), this.y + this.padding + row * (this.buttonHeight + 10), i);
        }
        this.makeNumberButton(this.x + this.padding + 1 * (this.buttonWidth + 10), this.y + this.padding + 3 * (this.buttonHeight + 10), 0);
        acceptButton = ig.game.spawnEntity(EntityCenteredTextBox, this.textCenter - 100, 400, {
          width: 200,
          height: 100,
          text: 'Answer It!',
          zIndex: 15
        });
        acceptButton.onclick = function() {
          return _this.delegate.resolve();
        };
        return this.children.push(acceptButton);
      },
      makeNumberButton: function(x, y, number) {
        var button,
          _this = this;
        button = ig.game.spawnEntity(EntityCenteredTextBox, x, y, {
          zIndex: 10,
          text: "" + number,
          width: this.buttonWidth,
          height: this.buttonHeight,
          font: this.font
        });
        button.onclick = function() {
          return _this.playerAnswer += "" + number;
        };
        return this.children.push(button);
      },
      draw: function() {
        this.parent();
        this.font.draw("Challenge", this.textCenter, 100, ig.Font.ALIGN.CENTER);
        this.bigFont.draw(this.question, this.textCenter, 150, ig.Font.ALIGN.CENTER);
        this.font.draw("Your Answer", this.textCenter, 250, ig.Font.ALIGN.CENTER);
        return this.bigFont.draw(this.playerAnswer, this.textCenter, 300, ig.Font.ALIGN.CENTER);
      }
    });
  });

}).call(this);
