// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.rectangle').requires('impact.entity').defines(function() {
    return window.EntityRectangle = ig.Entity.extend({
      init: function(x, y, settings) {
        this.x = x;
        this.y = y;
        this.width = settings.width;
        this.height = settings.height;
        this.backgroundColor = settings.backgroundColor;
        this.borderColor = settings.borderColor;
        return this.borderSize = parseInt(settings.borderSize);
      },
      update: function() {
        var _ref, _ref1;
        if (ig.input.pressed('click')) {
          if ((this.x < (_ref = ig.input.mouse.x) && _ref < this.x + this.width)) {
            if ((this.y < (_ref1 = ig.input.mouse.y) && _ref1 < this.y + this.height)) {
              return this.onclick();
            }
          }
        }
      },
      onclick: function() {
        return console.log('hello');
      },
      draw: function() {
        var ctx;
        ctx = ig.system.context;
        ctx.fillStyle = this.borderColor;
        ctx.fillRect(this.x, this.y, this.width, this.height);
        ctx.fillStyle = this.backgroundColor;
        return ctx.fillRect(this.x + this.borderSize, this.y + this.borderSize, this.width - this.borderSize * 2, this.height - this.borderSize * 2);
      }
    });
  });

}).call(this);
