// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.rectangle').requires('impact.entity').defines(function() {
    return window.EntityRectangle = ig.Entity.extend({
      children: [],
      init: function(x, y, settings) {
        this.x = x;
        this.y = y;
        this.width = settings.width;
        this.height = settings.height;
        this.backgroundColor = settings.backgroundColor || 'white';
        this.borderColor = settings.borderColor || 'black';
        this.borderSize = parseInt(settings.borderSize) || 2;
        this.ctx = ig.system.context;
        if (this.container) {
          this.x += this.container.x;
          this.y += this.container.y;
        }
        this.zIndex = settings.zIndex || 1;
        ig.game.sortEntitiesDeferred();
        this.timer = new ig.Timer();
        return this.timer.set(0.1);
      },
      update: function() {
        var _ref, _ref1;
        if (ig.input.pressed('click') && this.timer.delta() > 0) {
          if ((this.x < (_ref = ig.input.mouse.x) && _ref < this.x + this.width)) {
            if ((this.y < (_ref1 = ig.input.mouse.y) && _ref1 < this.y + this.height)) {
              return this.onclick();
            }
          }
        }
      },
      onclick: function() {
        return console.log('hello');
      },
      kill: function() {
        var child, _i, _len, _ref;
        _ref = this.children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          child.kill();
        }
        if (this.previous != null) {
          ig.game.spawnEntity(this.previous);
        }
        return this.parent();
      },
      draw: function() {
        this.ctx.fillStyle = this.borderColor;
        this.ctx.fillRect(this.x, this.y, this.width, this.height);
        this.ctx.fillStyle = this.backgroundColor;
        return this.ctx.fillRect(this.x + this.borderSize, this.y + this.borderSize, this.width - this.borderSize * 2, this.height - this.borderSize * 2);
      }
    });
  });

}).call(this);
