// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.screen').requires('game.entities.gui.rectangle').defines(function() {
    return window.EntityScreen = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.previous = settings.previous;
        this.parent(0, 0, settings);
        this.width = ig.system.width;
        this.height = ig.system.height;
        this.backgroundColor = '#ddd';
        this.borderColor = '#975';
        this.borderSize = 3;
        return ig.game.state = 'paused';
      }
    });
  });

}).call(this);
