// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gui.textBox').requires('game.entities.gui.rectangle').defines(function() {
    return window.EntityTextBox = EntityRectangle.extend({
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        this.text = settings.text;
        this.ctx.textAlign = 'left';
        this.ctx.textBaseline = 'top';
        return this.ctx.font = "20pt Arial";
      },
      draw: function() {
        this.parent();
        this.ctx.fillStyle = 'black';
        return this.drawText();
      },
      drawText: function() {
        return this.ctx.fillText(this.text, this.x, this.y);
      }
    });
  });

}).call(this);
