// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.chest').requires('impact.entity').defines(function() {
    return window.EntityChest = ig.Entity.extend({
      amount: 1,
      type: 'money',
      id: null,
      size: {
        x: 48,
        y: 48
      },
      font: new ig.Font('media/helvetica64EEE.png'),
      checkAgainst: ig.Entity.TYPE.A,
      used: null,
      killIfAlreadyUsed: function() {
        if (ig.game.storage.isSet("chest" + this.id)) {
          return this.kill();
        } else {
          return this.used = false;
        }
      },
      update: function() {
        if (this.used === null) {
          return this.killIfAlreadyUsed();
        }
      },
      check: function() {
        var message;
        if (this.type === 'money') {
          ig.game.stats.money += this.amount;
          message = ig.game.spawnEntity(EntityMessage, "+ $" + this.amount);
          message.pos.y += 50;
        }
        ig.game.storage.set("chest" + this.id, true);
        ig.game.record("chest", this.id, null, this.amount);
        return this.kill();
      },
      draw: function() {
        return this.font.draw("#", this.pos.x - this.offset.x - ig.game.screen.x, this.pos.y - this.offset.y - ig.game.screen.y);
      }
    });
  });

}).call(this);
