// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.dashboard').requires('impact.entity').defines(function() {
    return window.EntityDashboard = ig.Entity.extend({
      font: new ig.Font('media/helvetica30EEE.png'),
      spacing: 35,
      init: function() {
        return this.pos = {
          x: 5,
          y: 5
        };
      },
      draw: function() {
        this.font.draw("$" + ig.game.stats.money, this.pos.x, this.pos.y);
        this.drawProgressBar('addition', '+', 'blue', 0.25, 0);
        return this.drawProgressBar('subtraction', '- ', 'blue', 0.25, 1);
      },
      drawProgressBar: function(stat, symbol, fillColor, padPercent, position) {
        var padding, percent;
        this.font.draw(symbol + ig.game.stats[stat].level, this.pos.x, this.pos.y + this.spacing * (position + 1));
        padding = this.spacing * (1 + padPercent);
        this.drawRect(this.pos.x + padding, this.pos.y + padding + position * this.spacing, 200, this.spacing / 2, 'white');
        percent = ig.game.stats[stat].experience / ig.game.experienceRequired(ig.game.stats[stat].level);
        return this.drawRect(this.pos.x + padding, this.pos.y + padding + position * this.spacing, percent * 200, this.spacing / 2, fillColor);
      },
      drawRect: function(x, y, width, height, color) {
        var ctx, s;
        ctx = ig.system.context;
        s = ig.system.scale;
        ctx.fillStyle = color;
        return ctx.fillRect(x * s, y * s, width * s, height * s);
      }
    });
  });

}).call(this);
