// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.dashboard').requires('impact.entity').defines(function() {
    return window.EntityDashboard = ig.Entity.extend({
      font: new ig.Font('media/helvetica30EEE.png'),
      spacing: 35,
      init: function() {
        return this.pos = {
          x: 5,
          y: 5
        };
      },
      draw: function() {
        var padding, percent;
        this.font.draw("$" + ig.game.stats.money, this.pos.x, this.pos.y);
        this.font.draw("+" + ig.game.stats.addition.level, this.pos.x, this.pos.y + this.spacing);
        padding = this.spacing * 1.25;
        this.drawRect(this.pos.x + padding, this.pos.y + padding, 200, this.spacing / 2, 'white');
        percent = ig.game.stats.addition.experience / ig.game.experienceRequired(ig.game.stats.addition.level);
        return this.drawRect(this.pos.x + padding, this.pos.y + padding, percent * 200, this.spacing / 2, 'blue');
      },
      drawRect: function(x, y, width, height, color) {
        var ctx, s;
        ctx = ig.system.context;
        s = ig.system.scale;
        ctx.fillStyle = color;
        return ctx.fillRect(x * s, y * s, width * s, height * s);
      }
    });
  });

}).call(this);
