// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.dashboard').requires('impact.entity').defines(function() {
    return window.EntityDashboard = ig.Entity.extend({
      font: new ig.Font('media/helvetica30EEE.png'),
      spacing: 35,
      barLength: 200,
      init: function() {
        return this.pos = {
          x: 5,
          y: 5
        };
      },
      draw: function() {
        this.font.draw("$" + ig.game.stats.money, this.pos.x, this.pos.y);
        this.drawProgressBar('addition', '+', 'blue', 0.25, 0);
        return this.drawProgressBar('subtraction', '- ', 'blue', 0.25, 1);
      },
      drawProgressBar: function(stat, symbol, fillColor, padPercent, position) {
        var experience, experienceRequired, level, padding, percent, yValue;
        padding = this.spacing * (1 + padPercent);
        yValue = this.pos.y + padding + position * this.spacing;
        experience = ig.game.stats[stat].experience;
        level = ig.game.stats[stat].level;
        experienceRequired = ig.game.experienceRequired(level);
        percent = experience / experienceRequired;
        this.font.draw(symbol + level, this.pos.x, this.pos.y + this.spacing * (position + 1));
        this.drawRect(this.pos.x + padding, yValue, this.barLength, this.spacing / 2, 'white');
        this.drawRect(this.pos.x + padding, yValue, percent * this.barLength, this.spacing / 2, fillColor);
        return this.font.draw("" + experience + "/" + experienceRequired, this.pos.x + this.barLength + this.spacing * 2, yValue - 10);
      },
      drawRect: function(x, y, width, height, color) {
        var ctx, s;
        ctx = ig.system.context;
        s = ig.system.scale;
        ctx.fillStyle = color;
        return ctx.fillRect(x * s, y * s, width * s, height * s);
      }
    });
  });

}).call(this);
