// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.levelexit').requires('impact.entity').defines(function() {
    return window.EntityLevelexit = ig.Entity.extend({
      _wmDrawBox: true,
      _wmBoxColor: 'rgba(0, 0, 255, 0.7)',
      _wmScalable: true,
      size: {
        x: 48,
        y: 48
      },
      level: null,
      checkAgainst: ig.Entity.TYPE.A,
      newPos: {
        x: 740,
        y: 700
      },
      update: function() {},
      check: function(other) {
        if (other instanceof EntityPlayer) {
          return this.nextLevel();
        }
      },
      nextLevel: function() {
        var player;
        if (this.level) {
          ig.game.record("level", "" + this.level);
          player = ig.game.getEntitiesByType(EntityPlayer)[0];
          player.kill();
          return ig.game.changeLevel(this.level, this.newPos);
        }
      }
    });
  });

}).call(this);
