// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.player').requires('impact.entity').defines(function() {
    return window.EntityPlayer = ig.Entity.extend({
      collides: ig.Entity.COLLIDES.ACTIVE,
      type: ig.Entity.TYPE.A,
      additionLevel: 0,
      subtractionLevel: 0,
      size: {
        x: 32,
        y: 32
      },
      offset: {
        x: 8,
        y: 8
      },
      animSheet: new ig.AnimationSheet('media/puck.png', 48, 48),
      moveSpeed: 140,
      maxVel: {
        x: 200,
        y: 200
      },
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        return this.addAnim('idle', 0.1, [0, 1, 2, 3, 4, 4, 4, 4, 3, 2, 1]);
      },
      update: function() {
        var dx, dy;
        if (ig.game.state === 'main') {
          this.vel.x = 0;
          this.vel.y = 0;
          if (ig.input.state('click')) {
            dx = ig.input.mouse.x - ig.system.width / 2;
            dy = ig.input.mouse.y - ig.system.height / 2;
            if (Math.abs(dx) > Math.abs(dy)) {
              this.vel.x = Math.abs(dx) / dx * this.moveSpeed;
            } else {
              this.vel.y = Math.abs(dy) / dy * this.moveSpeed;
            }
          } else if (ig.input.state('up')) {
            this.vel.y = -this.moveSpeed;
          } else if (ig.input.state('down')) {
            this.vel.y = this.moveSpeed;
          } else {
            if (ig.input.state('left')) {
              this.vel.x = -this.moveSpeed;
            } else if (ig.input.state('right')) {
              this.vel.x = this.moveSpeed;
            }
          }
          return this.parent();
        }
      }
    });
  });

}).call(this);
