// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.player').requires('impact.entity').defines(function() {
    return window.EntityPlayer = ig.Entity.extend({
      collides: ig.Entity.COLLIDES.ACTIVE,
      type: ig.Entity.TYPE.A,
      additionLevel: 0,
      subtractionLevel: 0,
      size: {
        x: 48,
        y: 48
      },
      animSheet: new ig.AnimationSheet('media/puck.png', 48, 48),
      moveSpeed: 400,
      maxVel: {
        x: 800,
        y: 800
      },
      init: function(x, y, settings) {
        this.parent(x, y, settings);
        return this.addAnim('idle', 0.1, [0, 1, 2, 3, 4, 4, 4, 4, 3, 2, 1]);
      },
      update: function() {
        if (ig.game.state === 'main') {
          if (ig.input.state('up')) {
            this.vel.y = -this.moveSpeed;
            this.vel.x = 0;
          } else if (ig.input.state('down')) {
            this.vel.x = 0;
            this.vel.y = this.moveSpeed;
          } else {
            this.vel.y = 0;
            if (ig.input.state('left')) {
              this.vel.x = -this.moveSpeed;
            } else if (ig.input.state('right')) {
              this.vel.x = this.moveSpeed;
            } else {
              this.vel.x = 0;
            }
          }
          return this.parent();
        }
      }
    });
  });

}).call(this);
