// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.subtractionGate').requires('game.entities.gate').defines(function() {
    return window.EntitySubtractionGate = EntityGate.extend({
      gateType: 'subtraction',
      init: function(x, y, settings) {
        this.animSheet = new ig.AnimationSheet('media/tileset.png', this.spriteSize.x, this.spriteSize.y);
        this.parent(x, y, settings);
        return this.addAnim('idle', 1, [2]);
      },
      makeQuestion: function() {
        var high_number, n1, n2;
        n1 = this.equation();
        n2 = this.equation();
        high_number = n1 + n2;
        this.question = high_number + ' - ' + n2;
        return this.correct_answer = n1;
      },
      equation: function() {
        return Math.floor(Math.random() * Math.pow(this.difficulty + 1.5, 1.4));
      },
      failMessage: function() {
        return "The door won't budge./nYour powers of subtraction are not yet strong enough.";
      }
    });
  });

}).call(this);
