// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.switch').requires('impact.entity').defines(function() {
    return window.EntitySwitch = ig.Entity.extend({
      _wmDrawBox: true,
      _wmBoxColor: 'rgba(0, 0, 255, 0.7)',
      _wmScalable: true,
      size: {
        x: 48,
        y: 48
      },
      checkAgainst: ig.Entity.TYPE.A,
      key: null,
      value: null,
      check: function() {
        ig.game.switches[this.key] = this.value;
        console.log(ig.game.switches[this.key]);
        ig.game.save();
        return this.kill();
      },
      draw: function() {}
    });
  });

}).call(this);
