// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.timer').requires('impact.entity', 'impact.font', 'plugins.font').defines(function() {
    return window.EntityTimer = ig.Entity.extend({
      font: new Font('bold 30px Helvetica'),
      centering: ig.Font.ALIGN.CENTER,
      lifetime: 1,
      timer: null,
      init: function(message) {
        this.timer = new ig.Timer();
        this.timer.set(this.max());
        ig.Timer.timeScale = 1.2;
        return this.pos = {
          x: ig.system.width / 2,
          y: ig.system.height / 2
        };
      },
      update: function() {
        if (ig.game.state === 'paused') {
          this.timer.pause();
        } else {
          this.timer.unpause();
        }
        if (this.timeLeft() <= 0) {
          ig.game.goToCenter();
        }
        return this.parent();
      },
      timeLeft: function() {
        return Math.round(-1 * this.timer.delta());
      },
      draw: function() {
        return this.font.draw(this.timeLeft(), 860, 20, 'left', '#EEE');
      },
      max: function() {
        return 90 + 15 * ig.game.stats.timeIncreases;
      },
      change: function(amount) {
        return this.timer.set(-this.timer.delta() + amount);
      }
    });
  });

}).call(this);
