// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.treasure').requires('impact.entity').defines(function() {
    return window.EntityTreasure = ig.Entity.extend({
      amount: 1,
      id: null,
      size: {
        x: 48,
        y: 48
      },
      font: new ig.Font('media/helvetica64EEE.png'),
      checkAgainst: ig.Entity.TYPE.A,
      used: null,
      check: function() {
        var amountGained;
        if (ig.game.storage.isSet('treasure' + this.id)) {
          this.used = ig.game.storage.get('treasure' + this.id);
        }
        if (this.used) {
          amountGained = Math.round(this.amount / 3);
        } else {
          amountGained = this.amount;
        }
        ig.game.stats.money += amountGained;
        ig.game.storage.set('treasure' + this.id, 'true');
        ig.game.record('treasure', "" + this.id + " " + this.used, null, this.amountGained);
        ig.game.spawnEntity(EntityCompletedLevel, null, null, {
          money: amountGained,
          id: this.id
        });
        return this.kill();
      },
      draw: function() {
        return this.font.draw("#", this.pos.x - this.offset.x - ig.game.screen.x, this.pos.y - this.offset.y - ig.game.screen.y);
      }
    });
  });

}).call(this);
