// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gates.additionGate').requires('game.entities.gates.problemGate').defines(function() {
    return window.EntityAdditionGate = EntityProblemGate.extend({
      gateType: 'addition',
      init: function(x, y, settings) {
        this.animSheet = new ig.AnimationSheet('media/tileset.png', this.spriteSize.x, this.spriteSize.y);
        this.parent(x, y, settings);
        return this.addAnim('idle', 1, [1]);
      },
      makeQuestion: function() {
        var n1, n2;
        n1 = this.equation();
        n2 = this.equation();
        this.question = n1 + ' + ' + n2;
        return this.correct_answer = n1 + n2;
      },
      equation: function() {
        return Math.floor(Math.random() * Math.pow(this.difficulty + 1.5, 1.4));
      }
    });
  });

}).call(this);
