// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gates.divisionGate').requires('game.entities.gates.problemGate').defines(function() {
    return window.EntityDivisionGate = EntityProblemGate.extend({
      gateType: 'division',
      init: function(x, y, settings) {
        this.animSheet = new ig.AnimationSheet('media/tileset.png', this.spriteSize.x, this.spriteSize.y);
        this.parent(x, y, settings);
        return this.addAnim('idle', 1, [0]);
      },
      makeQuestion: function() {
        var n1, n2, product;
        n1 = this.equation();
        n2 = this.equation();
        product = n1 * n2;
        this.question = product + ' / ' + n1;
        return this.correct_answer = n2;
      },
      equation: function() {
        return Math.floor(Math.random() * Math.pow(this.difficulty + 1, 1.2));
      }
    });
  });

}).call(this);
