// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gates.jump').requires('game.entities.gates.gate').defines(function() {
    return window.EntityJump = EntityGate.extend({
      collides: ig.Entity.COLLIDES.NONE,
      gateType: 'jump',
      init: function(x, y, settings) {
        this.animSheet = new ig.AnimationSheet('media/tileset.png', this.spriteSize.x, this.spriteSize.y);
        this.parent(x, y, settings);
        return this.addAnim('idle', 1, [0]);
      },
      check: function(other) {
        var distance;
        console.log(other.vel);
        distance = 48 * (this.difficulty + 1);
        if (other.vel.x > 0) {
          return other.pos.x += distance;
        } else if (other.vel.x < 0) {
          return other.pos.x -= distance;
        } else if (other.vel.y > 0) {
          return other.pos.y += distance;
        } else if (other.vel.y < 0) {
          return other.pos.y -= distance;
        }
      }
    });
  });

}).call(this);
