// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.gates.moneyGate').requires('game.entities.gates.gate').defines(function() {
    return window.EntityMoneyGate = EntityGate.extend({
      gateType: 'money',
      amount: 1,
      id: null,
      paid: null,
      init: function(x, y, settings) {
        this.animSheet = new ig.AnimationSheet('media/tileset.png', this.spriteSize.x, this.spriteSize.y);
        this.parent(x, y, settings);
        this.addAnim('idle', 1, [0]);
        return this.id = this.difficulty;
      },
      killIfAlreadyPaid: function() {
        if (ig.game.storage.isSet("money" + this.id)) {
          return this.kill();
        } else {
          return this.paid = false;
        }
      },
      makeQuestion: function() {
        this.question = "Press 'y' to unlock for $" + this.amount;
        return this.correct_answer = "y";
      },
      reward: function() {
        ig.game.stats.money -= this.amount;
        ig.game.storage.set("money" + this.id);
        return ig.game.save();
      },
      passable: function() {
        return ig.game.stats.money >= this.amount;
      },
      update: function() {
        if (this.paid === null) {
          this.killIfAlreadyPaid();
        }
        if (ig.input.pressed('yes')) {
          this.player_answer = this.player_answer + 'y';
        }
        return this.parent();
      },
      failMessage: function() {
        return "You do not have enough money.  \nCome back when you have $" + this.amount;
      }
    });
  });

}).call(this);
