// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.money.cash').requires('game.entities.money.moneyGranter').defines(function() {
    return window.EntityCash = EntityMoneyGranter.extend({
      check: function() {
        this.parent();
        return ig.game.record('cash', "" + this.path, null, this.amount);
      },
      draw: function() {
        return this.font.draw("$", this.pos.x - this.offset.x - ig.game.screen.x, this.pos.y - this.offset.y - ig.game.screen.y);
      }
    });
  });

}).call(this);
