// Generated by CoffeeScript 1.3.3
(function() {

  ig.module('game.entities.money.chest').requires('game.entities.money.moneyGranter').defines(function() {
    return window.EntityChest = EntityMoneyGranter.extend({
      type: 'chest',
      id: null,
      used: null,
      killIfAlreadyUsed: function() {
        if (ig.game.storage.isSet("chest" + this.id)) {
          return this.kill();
        } else {
          return this.used = false;
        }
      },
      update: function() {
        if (this.used === null) {
          return this.killIfAlreadyUsed();
        }
      },
      check: function() {
        this.parent();
        ig.game.storage.set("chest" + this.id, true);
        return ig.game.record("chest", this.id, null, this.amount);
      },
      amount: function() {
        return this.baseline() * 30;
      },
      draw: function() {
        return this.font.draw("#", this.pos.x - this.offset.x - ig.game.screen.x, this.pos.y - this.offset.y - ig.game.screen.y);
      }
    });
  });

}).call(this);
